[package]
name = "ntz-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
publish = false

[[bin]]
name = "ntz"
path = "src/main.rs"

[lints]
workspace = true

[dependencies]
anyhow = "1.0.104"
clap = { version = "4.6.5", features = ["derive"] }
